### ISSUE TITLE
Cannot import get_adapters on Windows due to `fcntl` module not available

### ISSUE THREAD

**Issue by jpwright** [Bluetooth-Devices/bluetooth-adapters#101]
**Describe the bug**
Cannot import get_adapters on Windows due to `fcntl` module not being available.

**To Reproduce**

```
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.system()
'Windows'
>>> from bluetooth_adapters import get_adapters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<masked>\venv\Lib\site-packages\bluetooth_adapters\__init__.py", line 45, in <module>
    from .systems.linux_hci import get_adapters_from_hci
  File "<masked>\venv\Lib\site-packages\bluetooth_adapters\systems\linux_hci.py", line 4, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

**Additional context**

**Comment by jpwright** [comment]
Thanks @bdraco!
